"""empty message

Revision ID: 0b70116a08bc
Revises: 5382a32f63f0
Create Date: 2021-12-13 16:46:00.398357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b70116a08bc'
down_revision = '5382a32f63f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mybookings',
    sa.Column('bid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('craftsp_id', sa.Integer(), nullable=True),
    sa.Column('bdetails1_service', sa.String(length=100), nullable=False),
    sa.Column('btimedate_month', sa.String(length=55), nullable=False),
    sa.Column('btimedate_date', sa.String(length=20), nullable=False),
    sa.Column('btimedate_time', sa.String(length=20), nullable=False),
    sa.Column('bdetails1_location', sa.String(length=500), nullable=False),
    sa.Column('bookings_date', sa.DateTime(), nullable=True),
    sa.Column('bookings_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('bookings_delivery_status', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['craftsp_id'], ['craftsperson.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('bid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mybookings')
    # ### end Alembic commands ###
