"""empty message

Revision ID: 1b5f500cccf5
Revises: 5e0e41d820ad
Create Date: 2021-12-13 17:45:50.227617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b5f500cccf5'
down_revision = '5e0e41d820ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mybookings', sa.Column('bookings_status', sa.String(length=40), nullable=True))
    op.drop_column('mybookings', 'bookings_delivery_status')
    op.drop_column('mybookings', 'bookings_delivery_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mybookings', sa.Column('bookings_delivery_date', mysql.DATETIME(), nullable=True))
    op.add_column('mybookings', sa.Column('bookings_delivery_status', mysql.DATETIME(), nullable=True))
    op.drop_column('mybookings', 'bookings_status')
    # ### end Alembic commands ###
