"""empty message

Revision ID: 26376fb70ed0
Revises: 9b01734b8d31
Create Date: 2021-12-15 20:58:23.133018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26376fb70ed0'
down_revision = '9b01734b8d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_pic', sa.String(length=100), nullable=True))
    op.add_column('service', sa.Column('service_pic', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'service_pic')
    op.drop_column('category', 'category_pic')
    # ### end Alembic commands ###
