"""empty message

Revision ID: 313c078fb4d8
Revises: 66814991f747
Create Date: 2021-12-05 09:09:38.187550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313c078fb4d8'
down_revision = '66814991f747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timedate',
    sa.Column('timedate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timedate_month', sa.String(length=55), nullable=False),
    sa.Column('timedate_date', sa.String(length=20), nullable=False),
    sa.Column('timedate_time', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('timedate_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timedate')
    # ### end Alembic commands ###
