"""empty message

Revision ID: 3c2768b1f3db
Revises: 313c078fb4d8
Create Date: 2021-12-05 17:47:35.337580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2768b1f3db'
down_revision = '313c078fb4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('trx_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trx_custid', sa.Integer(), nullable=False),
    sa.Column('trx_amt', sa.Float(), nullable=False),
    sa.Column('trx_status', sa.String(length=40), nullable=False),
    sa.Column('trx_others', sa.String(length=255), nullable=True),
    sa.Column('trx_ref', sa.String(length=12), nullable=False),
    sa.Column('trx_ipaddress', sa.String(length=20), nullable=True),
    sa.Column('trx_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trx_custid'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('trx_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
