"""empty message

Revision ID: 5382a32f63f0
Revises: 3c2768b1f3db
Create Date: 2021-12-05 19:20:12.701903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5382a32f63f0'
down_revision = '3c2768b1f3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('details1', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'details1', 'customer', ['customer_id'], ['id'])
    op.add_column('timedate', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timedate', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timedate', type_='foreignkey')
    op.drop_column('timedate', 'customer_id')
    op.drop_constraint(None, 'details1', type_='foreignkey')
    op.drop_column('details1', 'customer_id')
    # ### end Alembic commands ###
