"""empty message

Revision ID: 5e0e41d820ad
Revises: 5af6a8f5ab12
Create Date: 2021-12-13 17:24:15.212423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e0e41d820ad'
down_revision = '5af6a8f5ab12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mybookings', sa.Column('btrx_ref', sa.String(length=12), nullable=True))
    op.drop_constraint('mybookings_ibfk_4', 'mybookings', type_='foreignkey')
    op.drop_column('mybookings', 'trx_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mybookings', sa.Column('trx_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('mybookings_ibfk_4', 'mybookings', 'transaction', ['trx_id'], ['trx_id'])
    op.drop_column('mybookings', 'btrx_ref')
    # ### end Alembic commands ###
