"""empty message

Revision ID: 66814991f747
Revises: f64635dc0e8e
Create Date: 2021-12-04 20:10:00.026523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66814991f747'
down_revision = 'f64635dc0e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('details1', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'details1', 'service', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'details1', type_='foreignkey')
    op.drop_column('details1', 'service_id')
    # ### end Alembic commands ###
