"""empty message

Revision ID: a814771f1745
Revises: 0b70116a08bc
Create Date: 2021-12-13 16:53:37.523384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a814771f1745'
down_revision = '0b70116a08bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mybookings', sa.Column('trx_ref', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mybookings', 'trx_ref')
    # ### end Alembic commands ###
