"""empty message

Revision ID: aef01d346982
Revises: 07a27bfd4cc1
Create Date: 2021-12-13 17:07:11.423575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aef01d346982'
down_revision = '07a27bfd4cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mybookings', sa.Column('trx_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mybookings', 'transaction', ['trx_id'], ['trx_id'])
    op.drop_column('mybookings', 'btrx_ref')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mybookings', sa.Column('btrx_ref', mysql.VARCHAR(length=12), nullable=False))
    op.drop_constraint(None, 'mybookings', type_='foreignkey')
    op.drop_column('mybookings', 'trx_id')
    # ### end Alembic commands ###
