"""empty message

Revision ID: d61a77d395d3
Revises: 26376fb70ed0
Create Date: 2021-12-21 11:32:10.422970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61a77d395d3'
down_revision = '26376fb70ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('craftsperson', sa.Column('craftsp_desc', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('craftsperson', 'craftsp_desc')
    # ### end Alembic commands ###
